---
### group_vars/DC1.yml

aaa_authentication:
  policies:
    local:
      allow_nopassword: true

# local users
local_users:
  # # Username with no password configured
  # - name: networkpw
  #   privilege: 15
  #   role: network-admin
  #   no_password: true

  # Username with a password
  - name: networkpw
    privilege: 15
    role: network-admin
    sha512_password: "$6$eucN5ngreuExDgwS$xnD7T8jO..GBDX0DUlp.hn.W7yW94xTjSanqgaQGBzPIhDAsyAl9N4oScHvOMvf07uVBFI4mKMxwdVEUVKgY/."

# OOB Management network default gateway
mgmt_gateway: 172.100.100.1
mgmt_interface: Management1

# dns servers.
name_servers:
  - 192.0.0.2
  - 192.0.0.3

# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
ntp_settings:
  server_vrf: use_mgmt_interface_vrf
  servers:
    - name: time.google.com
    - name: pool.ntp.org

# Establish exec/enable role when logging in to switch
aaa_authorization:
  exec:
    default: local
