---
### group_vars/DC1_FABRIC.yml

# Set the Fabric Name - must match an Ansible Inventory Group
fabric_name: DC1_FABRIC

# Set Design Type to l2ls
design:
  type: l2ls

# Ansible connectivity definitions
# eAPI connectivity via HTTPS is specified (as opposed to CLI via SSH)
ansible_connection: ansible.netcommon.httpapi
# Specifies that we are indeed using Arista EOS
ansible_network_os: arista.eos.eos
# This user/password must exist on the switches to enable Ansible access
ansible_user: admin
ansible_password: admin
# User escalation (to enter enable mode)
ansible_become: true
ansible_become_method: enable
# Use SSL (HTTPS)
ansible_httpapi_use_ssl: true
# Do not try to validate certs
ansible_httpapi_validate_certs: false

# Fabric defaults
cvp_host_1_name: "dxxcvp01"
cvp_host_1_ip: 10.10.10.7
cvp_host_2_name: "dxxcvp02"
cvp_host_2_ip: 10.10.10.8
cvp_host_3_name: "dxxcvp03"
cvp_host_3_ip: 10.10.10.9
default_mgmt_method: oob
mgmt_gateway: 172.100.100.1
mgmt_interface_vrf: mgmt
custom_mgmt_interface: Management1
mgmt_vrf_routing: false

# Spine Switches
l3spine:
  defaults:
    platform: 7280R3
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    mlag_peer_ipv4_pool: 192.168.0.0/31
    mlag_peer_l3_ipv4_pool: 192.168.0.2/31
    mlag_interfaces: [Ethernet47, Ethernet48]
    loopback_ipv4_pool: 192.168.160.0/18
  node_groups:
    - group: SPINES
      nodes:
        - name: SPINE1
          id: 1
          mgmt_ip: 172.100.100.101/24
          rack: "[DC1/MDF]"
        - name: SPINE2
          id: 2
          mgmt_ip: 172.100.100.102/24
          rack: "[DC2/MDF]"

# Leaf Switches
leaf:
  defaults:
    platform: 7050X3
    mlag_peer_ipv4_pool: 192.168.0.0/24
    uplink_switches: [SPINE1, SPINE2]
    uplink_interfaces: [Ethernet1, Ethernet2]
    mlag_interfaces: [Ethernet47, Ethernet48]
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384

  node_groups:
    - group: RACK1
      mlag: true
      filter:
        tags: [bluezone, greenzone]
      nodes:
        - name: LEAF1
          id: 1
          mgmt_ip: 172.100.100.105/24
          uplink_switch_interfaces: [Ethernet1, Ethernet1]
        - name: LEAF2
          id: 2
          mgmt_ip: 172.100.100.106/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
    - group: RACK2
      mlag: true
      filter:
        tags: [bluezone, orangezone]
      nodes:
        - name: LEAF3
          id: 3
          mgmt_ip: 172.100.100.107/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        - name: LEAF4
          id: 4
          mgmt_ip: 172.100.100.108/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]

#### Override for vEOS/cEOS Lab Caveats ####
p2p_uplinks_mtu: 1500

# Documentation
eos_designs_documentation:
  connected_endpoints: true
