---
#Setting serdes rates to 10G for speed-groups 10 (Et37-40), 11 (Et41-44), and 12 (ET45-48). # Additional configurations may be added in the future.
hardware:
  speed_groups:
    - speed_group: 10-12
      # Serdes speed like "10g" or "25g"
      serdes: 10g

port_profiles:
  - profile: PP-DEFAULTS
    spanning_tree_portfast: edge
    spanning_tree_bpduguard: enabled
    enabled: true
    raw_eos_cli: |
      no logging event link-status
      no snmp trap link-change
  - profile: PP-WAN1_vl440
    mode: access
    vlans: 440
    enabled: true
  - profile: PP-WAN2_vl504
    mode: access
    vlans: 504
    enabled: true

tenants:
  - name: WAN_SEGMENT
    l2vlans:
      - id: 440
        name: 'WAN1-TRANSIT'
        tags: [WAN1]
      - id: 504
        name: 'WAN2-TRANSIT'
        tags: [WAN2]

routers:
  - name: ismrr40
    adapters:
      - endpoint_ports: [ Te0/0/5 ]
        switch_ports: [ Ethernet47 ]
        switches: [ hsmwan40a ]
        profile: PP-WAN1_vl440
      - endpoint_ports: [ Te0/0/9 ]
        switch_ports: [ Ethernet47 ]
        switches: [ hsmwan41a ]
        profile: PP-WAN2_vl504
  - name: ismrr41
    adapters:
      - endpoint_ports: [ Te0/0/5 ]
        switch_ports: [ Ethernet48 ]
        switches: [ hsmwan40a ]
        profile: PP-WAN1_vl440
      - endpoint_ports: [ Te0/0/9 ]
        switch_ports: [ Ethernet48 ]
        switches: [ hsmwan41a ]
        profile: PP-WAN2_vl504

firewalls:
#WAN firewall
  - name: ismtmgpan40
    adapters:
      - endpoint_ports: [ Eth1/21 ]
        switch_ports: [ Ethernet49/1 ]
        switches: [ hsmwan40a ]
        profile: PP-WAN1_vl440
      - endpoint_ports: [ Eth1/22 ]
        switch_ports: [ Ethernet49/1 ]
        switches: [ hsmwan41a ]
        profile: PP-WAN2_vl504
  - name: ismtmgpan41
    adapters:
      - endpoint_ports: [ Eth1/21 ]
        switch_ports: [ Ethernet50/1 ]
        switches: [ hsmwan40a ]
        profile: PP-WAN1_vl440
      - endpoint_ports: [ Eth1/22 ]
        switch_ports: [ Ethernet50/1 ]
        switches: [ hsmwan41a ]
        profile: PP-WAN2_vl504
#Mgmt Firewall
  - name: ismmgtpan01
    adapters:
      - endpoint_ports: [ Eth1/13 ]
        switch_ports: [ Ethernet43 ]
        switches: [ hsmwan40a ]
        profile: PP-WAN1_vl440
      - endpoint_ports: [ Eth1/14 ]
        switch_ports: [ Ethernet43 ]
        switches: [ hsmwan41a ]
        profile: PP-WAN2_vl504
  - name: ismmgtpan02
    adapters:
      - endpoint_ports: [ Eth1/13 ]
        switch_ports: [ Ethernet44 ]
        switches: [ hsmwan40a ]
        profile: PP-WAN1_vl440
      - endpoint_ports: [ Eth1/14 ]
        switch_ports: [ Ethernet44 ]
        switches: [ hsmwan41a ]
        profile: PP-WAN2_vl504
#IoT-INET Firewall
  - name: ismpan98
    adapters:
      - endpoint_ports: [ Eth1/15 ]
        switch_ports: [ Ethernet45 ] 
        switches: [ hsmwan40a ]
        profile: PP-WAN1_vl440
      - endpoint_ports: [ Eth1/16 ]
        switch_ports: [ Ethernet45 ]
        switches: [ hsmwan41a ]
        profile: PP-WAN2_vl504
  - name: ismpan99
    adapters:
      - endpoint_ports: [ Eth1/15 ]
        switch_ports: [ Ethernet46 ]
        switches: [ hsmwan40a ]
        profile: PP-WAN1_vl440
      - endpoint_ports: [ Eth1/16 ]
        switch_ports: [ Ethernet46 ]
        switches: [ hsmwan41a ]
        profile: PP-WAN2_vl504

# monitor_sessions:
#   - name: SPANSession-to-WAN-FilterSwitch
#     sources:
#       - name: Ethernet1-48
#         direction: "both"
#     destinations:
#       - Ethernet53/1
