---
# Tenanat.yml hosts Common port-profiles, svi-profiles, endponits connections, Prefix-lists and route-maps 
network_services_keys:
  - name: Core-Tenant-OT
  - name: Core-Tenant-IT
  - name: Core-Tenant-IT-DC
  - name: Core-Tenant-IoT
  - name: Core-Tenant-ehs
  - name: Core-Tenant-Gnet

new_network_services_bgp_vrf_config: true

svi_profiles:
  - profile: svi_l3_defaults
    raw_eos_cli: |
      no ip proxy-arp
      no autostate

port_profiles: 
  PP_WAN-FIREWALL:
    mode: trunk
    speed: 100g
    vlans: 525,510,533
  PP_DMZ-FIREWALL:
    mode: trunk
    speed: 10g
    vlans: 581,589,633
  PP_Vendor-FIREWALL:
    mode: access
    speed: 25g
    vlans: 542
  PP_SCADA-FIREWALL:
    mode: access
    speed: 25g
    vlans: 541

firewalls:
  #WAN firewalls connection
  - name: ISMTMGPAN40
    adapters:
      - endpoint_ports: [Ethernet1/41, Ethernet1/41]
        switch_ports: [Ethernet3/5/1, Ethernet3/5/1]
        switches: [ISMCR01A, ISMCR02A]
        profile: PP_WAN-FIREWALL
        port_channel:
          description: MLAG PortChannel to WAN Firewalls
          mode: active
  - name: ISMTMGPAN41
    adapters:
      - endpoint_ports: [Ethernet1/42, Ethernet1/42]
        switch_ports: [Ethernet4/5/1, Ethernet4/5/1]
        switches: [ISMCR01A, ISMCR02A]
        profile: PP_WAN-FIREWALL
        port_channel:
          description: MLAG PortChannel to WAN Firewalls
          mode: active
  #IoT firewalls connection
  - name: ISMPAN98
    adapters:
      - endpoint_ports: [Ethernet1/15, Ethernet1/15]
        switch_ports: [Ethernet5/1, Ethernet5/1]
        switches: [ISMCR01A, ISMCR02A]
        profile: PP_DMZ-FIREWALL
        port_channel:
          description: MLAG PortChannel to DMZ Firewalls
          mode: active
  - name: ISMPAN99
    adapters:
      - endpoint_ports: [Ethernet1/16, Ethernet1/16]
        switch_ports: [Ethernet6/1, Ethernet6/1]
        switches: [ISMCR01A, ISMCR02A]
        profile: PP_DMZ-FIREWALL
        port_channel:
          description: MLAG PortChannel to DMZ Firewalls
          mode: active
  #Vendor firewalls connection
  - name: ISMTMGPAN48
    adapters:
      - endpoint_ports: [Ethernet1/23, Ethernet1/23]
        switch_ports: [Ethernet5/3, Ethernet5/3]
        switches: [ISMCR01A, ISMCR02A]
        profile: PP_Vendor-FIREWALL
        port_channel:
          description: MLAG PortChannel to Vendor Firewalls
          mode: active
  - name: ISMTMGPAN49
    adapters:
      - endpoint_ports: [Ethernet1/24, Ethernet1/24]
        switch_ports: [Ethernet6/3, Ethernet6/3]
        switches: [ISMCR01A, ISMCR02A]
        profile: PP_Vendor-FIREWALL
        port_channel:
          description: MLAG PortChannel to Vendor Firewalls
          mode: active
  #SCADA firewalls connection
  - name: ISMPAN60
    adapters:
      - endpoint_ports: [Ethernet1/15, Ethernet1/15]
        switch_ports: [Ethernet5/2, Ethernet5/2]
        switches: [ISMCR01A, ISMCR02A]
        profile: PP_SCADA-FIREWALL
        port_channel:
          description: MLAG PortChannel to SCADA Firewalls
          mode: active
  - name: ISMPAN61
    adapters:
      - endpoint_ports: [Ethernet1/16, Ethernet1/16]
        switch_ports: [Ethernet6/2, Ethernet6/2]
        switches: [ISMCR01A, ISMCR02A]
        profile: PP_SCADA-FIREWALL
        port_channel:
          description: MLAG PortChannel to SCADA Firewalls
          mode: active

#prefix-lists 
custom_structured_configuration_prefix_lists:
  - name: PL-FW-ALLOW-NETWORKS
    sequence_numbers:
      10:
        action: "permit 172.21.0.0/22 eq 32" # Supernet for Loopbacks at SM site
      20:
        action: "permit 192.168.160.0/20 eq 32" # Global Loopbacks
      30:
        action: "permit 192.0.2.0/24 eq 32" # IP Anycast #1
      40:
        action: "permit 198.51.100.0/24 eq 32" # IP Anycast #2
  - name: PL-FW-DENY-HOST-ROUTES
    sequence_numbers:
      10:
        action: "deny 0.0.0.0/0 ge 30"
  - name: PL-LOCAL-NETWORKS
    sequence_numbers:
      - sequence: 10
        action: "permit 10.208.0.0/13 le 29" # Supernet assigned to SM site
      - sequence: 20
        action: "permit 172.21.0.0/22 eq 32" # Supernet for Loopbacks at SM site
      - sequence: 30
        action: "permit 192.168.160.0/20 eq 32" # Global Loopbacks

custom_structured_configuration_route_maps:
  - name: RM-WANFW-OTVRF-OUT
    sequence_numbers:
      - sequence: 10
        type: permit
        match:
          - "ip address prefix-list PL-FW-ALLOW-NETWORKS"
      - sequence: 20
        type: permit
        match:
          - "ip address prefix-list PL-FW-DENY-HOST-ROUTES"
      # changing next hop change is recommended via an outgoing route-map on sessions to the firewall for a faster failover
      - sequence: 30
        type: permit
        set:
          - ip next-hop 10.210.249.65
  - name: RM-WANFW-ITVRF-OUT
    sequence_numbers:
      - sequence: 10
        type: permit
        match:
          - "ip address prefix-list PL-FW-ALLOW-NETWORKS"
      - sequence: 20
        type: permit
        match:
          - "ip address prefix-list PL-FW-DENY-HOST-ROUTES"
      # changing next hop change is recommended via an outgoing route-map on sessions to the firewall for a faster failover
      - sequence: 30
        type: permit
        set:
          - ip next-hop 10.210.241.65
  - name: RM-WANFW-IT-DCVRF-OUT
    sequence_numbers:
      - sequence: 10
        type: permit
        match:
          - "ip address prefix-list PL-FW-ALLOW-NETWORKS"
      - sequence: 20
        type: permit
        match:
          - "ip address prefix-list PL-FW-DENY-HOST-ROUTES"
      # changing next hop change is recommended via an outgoing route-map on sessions to the firewall for a faster failover
      - sequence: 30
        type: permit
        set:
          - ip next-hop 10.210.226.65
  - name: RM-WANFW-IoTVRF-OUT
    sequence_numbers:
      - sequence: 10
        type: permit
        match:
          - "ip address prefix-list PL-FW-ALLOW-NETWORKS"
      - sequence: 20
        type: permit
        match:
          - "ip address prefix-list PL-FW-DENY-HOST-ROUTES"
      # changing next hop change is recommended via an outgoing route-map on sessions to the firewall for a faster failover
      - sequence: 30
        type: permit
        set:
          - ip next-hop 110.210.241.73
  - name: RM-LOCAL-NETWORKS
    sequence_numbers:
      - sequence: 10
        type: permit
        match:
          - ip address prefix-list PL-LOCAL-NETWORKS

custom_structured_configuration_router_bgp:
  redistribute_routes:
    - source_protocol: connected
      route_map: RM-LOCAL-NETWORKS
  peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      type: null
      maximum_routes: null
      send_community: null
  address_family_ipv4:
    peer_groups:
      - name: IPv4-UNDERLAY-PEERS
        activate: null
  # eos_cli: 'no neighbor IPv4-UNDERLAY-PEERS peer group'