---

connected_endpoints_keys:
- description: circuits
  key: circuits
  type: circuits
- description: Firewall
  key: firewalls
  type: firewall

port_profiles:
  - profile: PP-DEFAULTS
    spanning_tree_portfast: edge
    spanning_tree_bpduguard: enabled
    enabled: true
    raw_eos_cli: |
      no logging event link-status
      no snmp trap link-change
  - profile: PP-INET-IoT1_vl1997
    mode: access
    vlans: 1997
    enabled: true
  - profile: PP-INET-IoT2_vl1998
    mode: access
    vlans: 1998
    enabled: true

tenants:
  - name: DMZ_SEGMENT
    l2vlans:
      - id: 1997
        name: 'INET-IoT1-TRANSIT'
        tags: [INET-IoT1]
      - id: 1998
        name: 'INET-IoT2-TRANSIT'
        tags: [INET-IoT2]

circuits:
  - name: CSMISP02
    adapters:
      - endpoint_ports: [ ISP#1 Circuit]
        switch_ports: [ Ethernet49 ]
        switches: [ hsmdmz100a ]
        mode: "access"
        enabled: true
        profile: PP-INET-IoT1_vl1997

firewalls:
  - name: ismpan98
    adapters:
      - endpoint_ports: [ Eth13 ]
        switch_ports: [ Ethernet51 ]
        switches: [ hsmdmz100a ]
        profile: PP-INET-IoT1_vl1997
      - endpoint_ports: [ Eth14 ]
        switch_ports: [ Ethernet51 ]
        switches: [ hsmdmz101a ]
        profile: PP-INET-IoT2_vl1998
  - name: ismpan99
    adapters:
      - endpoint_ports: [ Eth13 ]
        switch_ports: [ Ethernet52 ]
        switches: [ hsmdmz100a ]
        profile: PP-INET-IoT1_vl1997
      - endpoint_ports: [ Eth14 ]
        switch_ports: [ Ethernet52 ]
        switches: [ hsmdmz101a ]
        profile: PP-INET-IoT2_vl1998