---
Core-Tenant-IoT:
  - name: "Core-Tenant-IoT"
    vrfs:
      - name: IoT
        mlag_ibgp_peering_vlan: "4089"
        mlag_ibgp_peering_ipv4_pool: 192.168.0.4/31
        svis:
          633:
            name: IoTFW-TRANSIT-IoTVRF
            enabled: true
            ip_virtual_router_addresses:
              - 10.210.241.73
            nodes:
              - node: ISMCR01A
                ip_address: 10.210.241.74/29
              - node: ISMCR02A
                ip_address: 10.210.241.75/29
        l3_interfaces:
          - interfaces:
                - Ethernet3/3/1.633
                - Ethernet4/3/1.633
                - Ethernet3/3/1.633
                - Ethernet4/3/1.633
            nodes:
                - ISMCR01A
                - ISMCR01A
                - ISMCR02A
                - ISMCR02A
            ip_addresses:
                - 10.210.241.8/31
                - 10.210.241.12/31
                - 10.210.241.10/31
                - 10.210.241.14/31
            descriptions:
              - '[L]_ISMS1ITBL01A-Eth1/1-IoTVRF'
              - '[L]_ISMS1ITBL02A-Eth1/1-IoTVRF'
              - '[L]_ISMS1ITBL01A-Eth2/1-IoTVRF'
              - '[L]_ISMS1ITBL02A-Eth2/1-IoTVRF'
        bgp_peer_groups:
          - name: IT-BL-EBGP-PEERS-IoTVRF
            nodes:
              - ISMCR01A
              - ISMCR02A
            remote_as: "65120.31200"
            maximum_routes: 0
            password: "{{ '{{ vault.bgp.password }}' | arista.avd.encrypt(passwd_type='bgp', key='IT-BLLF-EBGP-PEERS-IoTVRF') }}"
          # to the IoT Firewall
          - name: DMZFW-EBGP-PEERS
            nodes:
              - ISMCR01A
              - ISMCR02A
            remote_as: "65120.98"
            maximum_routes: 0
            password: "{{ '{{ vault.bgp.password }}' | arista.avd.encrypt(passwd_type='bgp', key='IoTFW-EBGP-PEERS') }}"
        bgp_peers:
          - ip_address: 10.210.241.9
            description: ISMS1ITBL01A-Eth1/1-IoTVRF
            peer_group: IT-BLLF-EBGP-PEERS-IoTVRF
            nodes:
              - ISMCR01A
          - ip_address: 10.210.241.13
            description: ISMS1ITBL02A-Eth1/1-IoTVRF
            peer_group: IT-BLLF-EBGP-PEERS-IoTVRF
            nodes:
              - ISMCR01A
          - ip_address: 10.210.241.11
            description: ISMS1ITBL01A-Eth2/1-IoTVRF
            peer_group: IT-BLLF-EBGP-PEERS-IoTVRF
            nodes:
              - ISMCR02A
          - ip_address: 10.210.241.15
            description: ISMS1ITBL02A-Eth2/1-IoTVRF
            peer_group: IT-BLLF-EBGP-PEERS-IoTVRF
            nodes:
              - ISMCR02A
          #DMZ FWL EBGP PEERS
          - ip_address: 10.210.241.78
            description: DMZFW-VIP-IoTVRF
            peer_group: DMZFW-EBGP-PEERS
            nodes:
              - ISMCR01A
              - ISMCR02A
            # changing next hop change is recommended via an outgoing route-map on sessions to the firewall for a faster failover
            # set_ipv4_next_hop: 10.210.241.73
            route_map_out: RM-DMZFW-IoT-VRF-OUT
        structured_config:
          route_maps:
            - name: RM-DMZFW-IoT-VRF-OUT
              sequence_numbers:
                - sequence: 10
                  type: permit
                  match:
                    - "ip address prefix-list PL-DMZFW-DENY-HOST-ROUTES"
                - sequence: 20
                  type: permit
                  set:
                    - ip next-hop 10.210.241.73 #TBA

prefix_lists:
  - name: PL-DMZFW-DENY-HOST-ROUTES
    sequence_numbers:
      10:
        action: "deny 0.0.0.0/0 ge 30"