---
network_services_keys:
  - name: Core-Tenant-OT
  - name: Core-Tenant-IT
  - name: Core-Tenant-IT-DC
  - name: Core-Tenant-IoT
  - name: Core-Tenant-ehs
  - name: Core-Tenant-Gnet

new_network_services_bgp_vrf_config: true

# bgp_peer_groups:
#   ipv4_underlay_peers:
#     name: WANFW-EBGP-PEERS

port_profiles: 
  TRUNK_100G_WAN Firewall:
    mode: trunk
    speed: 100g
    spanning_tree_portfast: edge
    vlans: 525,510,533
  Access_10G_IoT_Firewall:
    mode: access
    speed: 10g
    spanning_tree_portfast: edge
    vlans: 633
  Access_25G_Vendor_Firewall:
    mode: access
    speed: 25g
    spanning_tree_portfast: edge
    vlans: 542
  Access_25G_SCADA_Firewall:
    mode: access
    speed: 25g
    spanning_tree_portfast: edge
    vlans: 541

firewalls:
  #WAN firewalls connection
  - name: ISMTMGPAN40
    adapters:
      - endpoint_ports: [Ethernet1/41, Ethernet1/41]
        switch_ports: [Ethernet3/5/1, Ethernet3/5/1]
        switches: [ISMCR01A, ISMCR02A]
        profile: TRUNK_100G_WAN Firewall
        port_channel:
          description: MLAG PortChannel to WAN Firewalls
          mode: active
  - name: ISMTMGPAN41
    adapters:
      - endpoint_ports: [Ethernet1/42, Ethernet1/42]
        switch_ports: [Ethernet4/5/1, Ethernet4/5/1]
        switches: [ISMCR01A, ISMCR02A]
        profile: TRUNK_100G_WAN Firewall
        port_channel:
          description: MLAG PortChannel to WAN Firewalls
          mode: active
  #IoT firewalls connection
  - name: ISMPAN98
    adapters:
      - endpoint_ports: [Ethernet1/15, Ethernet1/15]
        switch_ports: [Ethernet5/1, Ethernet5/1]
        switches: [ISMCR01A, ISMCR02A]
        profile: Access_10G_IoT_Firewall
        port_channel:
          description: MLAG PortChannel to IoT Firewalls
          mode: active
  - name: ISMPAN99
    adapters:
      - endpoint_ports: [Ethernet1/16, Ethernet1/16]
        switch_ports: [Ethernet6/1, Ethernet6/1]
        switches: [ISMCR01A, ISMCR02A]
        profile: Access_10G_IoT_Firewall
        port_channel:
          description: MLAG PortChannel to IoT Firewalls
          mode: active
  #Vendor firewalls connection
  - name: ISMTMGPAN48
    adapters:
      - endpoint_ports: [Ethernet1/23, Ethernet1/23]
        switch_ports: [Ethernet5/3, Ethernet5/3]
        switches: [ISMCR01A, ISMCR02A]
        profile: Access_25G_Vendor_Firewall
        port_channel:
          description: MLAG PortChannel to Vendor Firewalls
          mode: active
  - name: ISMTMGPAN49
    adapters:
      - endpoint_ports: [Ethernet1/24, Ethernet1/24]
        switch_ports: [Ethernet6/3, Ethernet6/3]
        switches: [ISMCR01A, ISMCR02A]
        profile: Access_25G_Vendor_Firewall
        port_channel:
          description: MLAG PortChannel to Vendor Firewalls
          mode: active
  #SCADA firewalls connection
  - name: ISMPAN60
    adapters:
      - endpoint_ports: [Ethernet1/15, Ethernet1/15]
        switch_ports: [Ethernet5/2, Ethernet5/2]
        switches: [ISMCR01A, ISMCR02A]
        profile: Access_25G_SCADA_Firewall
        port_channel:
          description: MLAG PortChannel to SCADA Firewalls
          mode: active
  - name: ISMPAN61
    adapters:
      - endpoint_ports: [Ethernet1/16, Ethernet1/16]
        switch_ports: [Ethernet6/2, Ethernet6/2]
        switches: [ISMCR01A, ISMCR02A]
        profile: Access_25G_SCADA_Firewall
        port_channel:
          description: MLAG PortChannel to SCADA Firewalls
          mode: active

#prefix-lists 
prefix_lists:
  - name: PL-DMZFW-DENY-HOST-ROUTES
    sequence_numbers:
      10:
        action: "deny 0.0.0.0/0 ge 30"

svi_profiles:
  - profile: svi_l3_defaults
    raw_eos_cli: |
      no ip proxy-arp
      no autostate

custom_structured_configuration_prefix_lists:
  - name: PL-LOCAL-NETWORKS
    # sequence_numbers:
    #   - sequence: 10
    #     action: permit 10.215.192.0/23
    
custom_structured_configuration_route_maps:
  - name: RM-LOCAL-NETWORKS
    sequence_numbers:
      - sequence: 10
        type: permit
        match:
          - ip address prefix-list PL-LOCAL-NETWORKS

custom_structured_configuration_router_bgp:
  redistribute_routes:
    - source_protocol: connected
      route_map: RM-LOCAL-NETWORKS
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: null
    maximum_routes: null
    send_community: null
  address_family_ipv4:
    peer_groups:
      - name: IPv4-UNDERLAY-PEERS
        activate: null
  eos_cli: 'no neighbor IPv4-UNDERLAY-PEERS peer group'
  