---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: SHERMAN_FABRIC

dc_name: SM-DC2_FABRIC

description_prefix: "[L]"

#sflow collector
sflow_dest: sflowle03

design:
  type: l3ls-evpn

# Fabric CVP Variables for global.yml
cvp_host_1_name: dsmcvp01
cvp_host_1_ip: 10.210.80.7
cvp_host_2_name: dsmcvp02
cvp_host_2_ip: 10.210.80.8
cvp_host_3_name: dsmcvp03
cvp_host_3_ip: 10.210.80.9

mgmt_gateway: "{{ ansible_host | ansible.utils.ipaddr('network/prefix') | ansible.utils.ipaddr('1') | ansible.utils.ipaddr('address') }}"
mgmt_interface_vrf: mgmt
custom_mgmt_interface: "{{ switch.mgmt_interface }}"

# Disable vlan aware bundles
evpn_vlan_aware_bundles: false

# This feature allows IPv6 underlay routing protocol with RFC5549 addresses to be used along with IPv4 advertisements as VXLAN tunnel endpoints.
underlay_rfc5549: true

# bgp peer groups passwords
bgp_peer_groups:
  ipv4_underlay_peers:
    password: "{{ '{{ vault.bgp.password }}' | arista.avd.encrypt(passwd_type='bgp', key='ipv4_underlay_peers') }}"
  evpn_overlay_peers:
    password: "{{ '{{ vault.bgp.password }}' | arista.avd.encrypt(passwd_type='bgp', key='evpn_overlay_peers') }}"
  mlag_ipv4_underlay_peer:
    password: "{{ '{{ vault.bgp.password }}' | arista.avd.encrypt(passwd_type='bgp', key='mlag_ipv4_underlay_peer') }}"

bgp_maximum_paths: 128
bgp_ecmp: 128

# Spine Switches
spine:
  defaults:
    platform: 7280R3
    bgp_as: "65120.12100"
    loopback_ipv4_pool: 172.21.1.0/24
    bgp_defaults:
      - bgp asn notation asdot
      - distance bgp 20 200 200
      - timers bgp 5 15
      - neighbor default send-community
  nodes:
    ISMDC2SP01A:
      id: 1
      mgmt_ip: 10.210.80.35/21
    ISMDC2SP02A:
      id: 2
      mgmt_ip: 10.210.80.36/21
    ISMDC2SP03A:
      id: 3
      mgmt_ip: 10.210.80.37/21

# Leaf switch groups
l3leaf:
  defaults:
    # virtual router mac for VNIs assigned to Leaf switches
    virtual_router_mac_address: 00:aa:aa:aa:aa:aa
    platform: 7280R3
    loopback_ipv4_pool: 172.21.1.0/24
    loopback_ipv4_offset: 3
    vtep_loopback_ipv4_pool: 10.210.232.0/24
    uplink_switches: [ISMDC2SP01A, ISMDC2SP02A, ISMDC2SP03A ]
    uplink_interfaces: [ Ethernet49/1, Ethernet50/1, Ethernet51/1 ]
    mlag_interfaces: [ Ethernet55/1, Ethernet56/1 ]
    mlag_peer_ipv4_pool: 192.168.0.0/31
    mlag_peer_l3_ipv4_pool: 192.168.0.2/31
    mlag_port_channel_id: 4094
    mlag_domain_id: MLAG
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    bgp_defaults:
      - bgp asn notation asdot
      - distance bgp 20 200 200
      - timers bgp 5 15
      - neighbor default send-community
  node_groups:
    - group: DC2_LEAF1_2
      bgp_as: "65120.12201"
      nodes:
        DC2-CL1:
          id: 1
          mgmt_ip: 10.210.80.40/21
          uplink_switch_interfaces: [ Ethernet3/1, Ethernet3/1, Ethernet3/1 ]
        DC2-CL2:
          id: 2
          mgmt_ip: 10.210.80.41/21
          uplink_switch_interfaces: [ Ethernet4/1, Ethernet4/1, Ethernet4/1 ]
    - group: DC2_LEAF3_4
      bgp_as: "65120.12202"
      nodes:
        DC2-CL3:
          id: 3
          mgmt_ip: 10.210.80.42/21
          uplink_switch_interfaces: [ Ethernet5/1, Ethernet5/1, Ethernet5/1 ]
        DC2-CL4:
          id: 4
          mgmt_ip: 10.210.80.43/21
          uplink_switch_interfaces: [ Ethernet6/1, Ethernet6/1, Ethernet6/1 ]
    - group: DC2_LEAF5_6
      bgp_as: "65120.12203"
      nodes:
        DC2-CL5:
          id: 5
          mgmt_ip: 10.210.80.44/21
          uplink_switch_interfaces: [ Ethernet7/1, Ethernet7/1, Ethernet7/1 ]
        DC2-CL6:
          id: 6
          mgmt_ip: 10.210.80.45/21
          uplink_switch_interfaces: [ Ethernet8/1, Ethernet8/1, Ethernet8/1 ]
    - group: DC2_LEAF7_8
      bgp_as: "65120.12204"
      nodes:
        DC2-CL7:
          id: 7
          mgmt_ip: 10.210.80.46/21
          uplink_switch_interfaces: [ Ethernet9/1, Ethernet9/1, Ethernet9/1 ]
        DC2-CL8:
          id: 8
          mgmt_ip: 10.210.80.47/21
          uplink_switch_interfaces: [ Ethernet10/1, Ethernet10/1, Ethernet10/1 ]
    - group: DC2_LEAF9_10
      bgp_as: "65120.12205"
      nodes:
        DC2-CL9:
          id: 9
          mgmt_ip: 10.210.80.48/21
          uplink_switch_interfaces: [ Ethernet11/1, Ethernet11/1, Ethernet11/1 ]
        DC2-CL10:
          id: 10
          mgmt_ip: 10.210.80.49/21
          uplink_switch_interfaces: [ Ethernet12/1, Ethernet12/1, Ethernet12/1 ]
    - group: DC2_LEAF11_12
      bgp_as: "65120.12206"
      nodes:
        DC2-CL11:
          id: 11
          mgmt_ip: 10.210.80.50/21
          uplink_switch_interfaces: [ Ethernet13/1, Ethernet13/1, Ethernet13/1 ]
        DC2-CL12:
          id: 12
          mgmt_ip: 10.210.80.51/21
          uplink_switch_interfaces: [ Ethernet14/1, Ethernet14/1, Ethernet14/1 ]
    - group: DC2_LEAF13_14
      bgp_as: "65120.12207"
      nodes:
        DC2-CL13:
          id: 13
          mgmt_ip: 10.210.80.52/21
          uplink_switch_interfaces: [ Ethernet15/1, Ethernet15/1, Ethernet15/1 ]
        DC2-CL14:
          id: 14
          mgmt_ip: 10.210.80.53/21
          uplink_switch_interfaces: [ Ethernet16/1, Ethernet16/1, Ethernet16/1 ]
    - group: DC2_LEAF15_16
      bgp_as: "65120.12208"
      nodes:
        DC2-CL15:
          id: 15
          mgmt_ip: 10.210.80.54/21
          uplink_switch_interfaces: [ Ethernet17/1, Ethernet17/1, Ethernet17/1 ]
        DC2-CL16:
          id: 16
          mgmt_ip: 10.210.80.55/21
          uplink_switch_interfaces: [ Ethernet18/1, Ethernet18/1, Ethernet18/1 ]
    - group: DC2_LEAF17_18
      bgp_as: "65120.12209"
      nodes:
        DC2-CL17:
          id: 17
          mgmt_ip: 10.210.80.56/21
          uplink_switch_interfaces: [ Ethernet19/1, Ethernet19/1, Ethernet19/1 ]
        DC2-CL18:
          id: 18
          mgmt_ip: 10.210.80.57/21
          uplink_switch_interfaces: [ Ethernet20/1, Ethernet20/1, Ethernet20/1 ]
    - group: DC2_LEAF19_20
      bgp_as: "65120.12210"
      nodes:
        DC2-CL19:
          id: 19
          mgmt_ip: 10.210.80.58/21
          uplink_switch_interfaces: [ Ethernet21/1, Ethernet21/1, Ethernet21/1 ]
        DC2-CL20:
          id: 20
          mgmt_ip: 10.210.80.59/21
          uplink_switch_interfaces: [ Ethernet22/1, Ethernet22/1, Ethernet22/1 ]
    - group: DC2_BLEAFS
      filter:
        tags: [stretch, sFLOW]
      bgp_as: "65120.12200"
      uplink_interfaces: [ Ethernet25/1, Ethernet26/1, Ethernet27/1 ]
      mlag_interfaces: [ Ethernet31/1, Ethernet32/1 ]
      evpn_gateway:
        remote_peers:
          - hostname: ISMDC1BL01A
            ip_address: 10.210.80.13
            bgp_as: "65120.11200"
          - hostname: ISMDC1BL02A
            ip_address: 10.210.80.14
            bgp_as: "65120.11200"
        evpn_l2:
          enabled: true
        evpn_l3:
          enabled: true
          inter_domain: true
      nodes:
        ISMDC2BL01A:
          id: 21
          mgmt_ip: 10.210.80.38/21
          uplink_switch_interfaces: [ Ethernet1/1, Ethernet1/1, Ethernet1/1 ]
        ISMDC2BL02A:
          id: 22
          mgmt_ip: 10.210.80.39/21
          uplink_switch_interfaces: [ Ethernet2/1, Ethernet2/1, Ethernet2/1 ]

    
p2p_uplinks_mtu: 9214

# Adjust default bfd values #TBD with TI
bfd_multihop:
  interval: 3000
  min_rx: 3000
  multiplier: 3

fabric_ip_addressing:
  mlag:
    algorithm: same_subnet
