---
Core_Tenant_IT-DC:
  - name: "Core_Tenant_IT-DC"
    vrfs:
      - name: IT-DC
        enable_mlag_ibgp_peering_vrfs: false
        svis:
          510:
            name: WANFW-TRANSIT-IT-DCVRF
            enabled: true
            profile: svi_l3_defaults
            ip_virtual_router_addresses:
              - 10.210.226.65
            nodes:
              - node: ismcr01a
                ip_address: 10.210.226.66/29
              - node: ismcr02a
                ip_address: 10.210.226.67/29
        l3_interfaces:
          - interfaces:
                - Ethernet3/1/1.510
                - Ethernet4/1/1.510
                - Ethernet3/2/1.510
                - Ethernet4/2/1.510
                - Ethernet3/1/1.510
                - Ethernet4/1/1.510
                - Ethernet3/2/1.510
                - Ethernet4/2/1.510
            nodes:
                - ismcr01a
                - ismcr01a
                - ismcr01a
                - ismcr01a
                - ismcr02a
                - ismcr02a
                - ismcr02a
                - ismcr02a
            ip_addresses:
                - 10.210.226.24/31
                - 10.210.226.28/31
                - 10.210.234.16/31
                - 10.210.234.20/31
                - 10.210.226.26/31
                - 10.210.226.30/31
                - 10.210.234.18/31
                - 10.210.234.22/31
            descriptions:
              - '[L]_ismdc1bl01a-Eth1/1-IT-DCVRF'
              - '[L]_ismdc1bl02a-Eth1/1-IT-DCVRF'
              - '[L]_ismdc2bl01a-Eth1/1-IT-DCVRF'
              - '[L]_ismdc2bl02a-Eth1/1-IT-DCVRF'
              - '[L]_ismdc1bl01a-Eth2/1-IT-DCVRF'
              - '[L]_ismdc1bl02a-Eth2/1-IT-DCVRF'
              - '[L]_ismdc2bl01a-Eth2/1-IT-DCVRF'
              - '[L]_ismdc2bl02a-Eth2/1-IT-DCVRF'
        bgp_peer_groups:
          - name: DC1-BL-EBGP-PEERS-IT-DCVRF
            nodes:
              - ismcr01a
              - ismcr02a
            remote_as: "65120.11200"
            # Originate default from firewalls towards DC1 Border Leaf switches in IT-DC VRF
            default_originate:
              enabled: true
            maximum_routes: 0
          - name: DC2-BL-EBGP-PEERS-IT-DCVRF
            nodes:
              - ismcr01a
              - ismcr02a
            remote_as: "65120.12200"
            # Originate default from firewalls towards DC2 Border Leaf switches in IT-DC VRF
            default_originate:
              enabled: true
            maximum_routes: 0
        bgp_peers:
          - ip_address: 10.210.226.25
            description: DC1-BL1-Eth1/1-IT-DCVRF
            peer_group: DC1-BL-EBGP-PEERS-IT-DCVRF
            nodes:
              - ismcr01a
          - ip_address: 10.210.226.29
            description: DC1-BL2-Eth1/1-IT-DCVRF
            peer_group: DC1-BL-EBGP-PEERS-IT-DCVRF
            nodes:
              - ismcr01a
          - ip_address: 10.210.226.27
            description: DC1-BL1-Eth2/1-IT-DCVRF
            peer_group: DC1-BL-EBGP-PEERS-IT-DCVRF
            nodes:
              - ismcr02a
          - ip_address: 10.210.226.31
            description: DC1-BL2-Eth2/1-IT-DCVRF
            peer_group: DC1-BL-EBGP-PEERS-IT-DCVRF
            nodes:
              - ismcr02a
          - ip_address: 10.210.234.17
            description: DC2-BL1-Eth1/1-IT-DCVRF
            peer_group: DC2-BL-EBGP-PEERS-IT-DCVRF
            nodes:
              - ismcr01a
          - ip_address: 10.210.234.21
            description: DC2-BL2-Eth1/1-IT-DCVRF
            peer_group: DC2-BL-EBGP-PEERS-IT-DCVRF
            nodes:
              - ismcr01a
          - ip_address: 10.210.234.19
            description: DC2-BL1-Eth2/1-IT-DCVRF
            peer_group: DC2-BL-EBGP-PEERS-IT-DCVRF
            nodes:
              - ismcr02a
          - ip_address: 10.210.234.23
            description: DC2-BL2-Eth2/1-IT-DCVRF
            peer_group: DC2-BL-EBGP-PEERS-IT-DCVRF
            nodes:
              - ismcr02a
            # changing next hop change is recommended via an outgoing route-map on sessions to the firewall for a faster failover
          - ip_address: 10.210.226.70
            description: WANFW-IP-IT-DCVRF
            peer_group: WANFW-EBGP-PEERS
            nodes:
              - ismcr01a
              - ismcr02a
            route_map_out: RM-WANFW-IT-DCVRF-OUT
        structured_config:
          router_bgp:
            vrfs:
              - name: IT-DC
                redistribute_routes:
                  - source_protocol: connected
                    route_map: RM-LOCAL-NETWORKS
        static_routes:
          - destination_address_prefix: 0.0.0.0/0
            gateway: 10.210.226.70
            name: ismtmgpan40-41-IT-DCVRF
            metric: 225
            distance: 225
            nodes:
              - ismcr01a
              - ismcr02a
