---
Core-Tenant-ehs:
  - name: "Core-Tenant-ehs"
    vrfs:
      - name: ehs
        enable_mlag_ibgp_peering_vrfs: false
        svis:
          581:
            name: DMZFW-TRANSIT-ehsVRF
            enabled: true
            profile: svi_l3_defaults
            ip_virtual_router_addresses:
              - 10.210.241.121
            nodes:
              - node: ISMCR01A
                ip_address: 10.210.241.122/29
              - node: ISMCR02A
                ip_address: 10.210.241.123/29
        l3_interfaces:
          - interfaces:
                - Ethernet3/4/1.581
                - Ethernet4/4/1.581
                - Ethernet3/4/1.581
                - Ethernet4/4/1.581
            nodes:
                - ISMCR01A
                - ISMCR01A
                - ISMCR02A
                - ISMCR02A
            ip_addresses:
                - 10.210.241.32/31
                - 10.210.241.34/31
                - 10.210.241.36/31
                - 10.210.241.38/31
            descriptions:
              - '[L]_ISMITMSC01A-Eth49/1-ehsVRF'
              - '[L]_ISMITMSC02A-Eth49/1-ehsVRF'
              - '[L]_ISMITMSC01A-Eth50/1-ehsVRF'
              - '[L]_ISMITMSC02A-Eth50/1-ehsVRF'
        bgp_peer_groups:
          - name: MISC-CORES-EBGP-PEERS-ehsVRF
            nodes:
              - ISMCR01A
              - ISMCR02A
            remote_as: "65120.10"
            maximum_routes: 0
          # to the DMZ Firewall
          - name: DMZFW-EBGP-PEERS-ehsVRF
            nodes:
              - ISMCR01A
              - ISMCR02A
            remote_as: "65120.98"
            maximum_routes: 0
        bgp_peers:
          # to the Misc-Core 
          - ip_address: 10.210.241.33
            description: ISMITMSC01A-Eth49/1-ehsVRF
            peer_group: MISC-CORES-EBGP-PEERS-ehsVRF
            nodes:
              - ISMCR01A
          - ip_address: 10.210.241.35
            description: ISMITMSC02A-Eth49/1-ehsVRF
            peer_group: MISC-CORES-EBGP-PEERS-ehsVRF
            nodes:
              - ISMCR01A
          - ip_address: 10.210.241.37
            description: ISMITMSC01A-Eth50/1-ehsVRF
            peer_group: MISC-CORES-EBGP-PEERS-ehsVRF
            nodes:
              - ISMCR02A
          - ip_address: 10.210.241.39
            description: ISMITMSC02A-Eth50/1-ehsVRF
            peer_group: MISC-CORES-EBGP-PEERS-ehsVRF
            nodes:
              - ISMCR02A
          - ip_address: 10.210.241.126
            description: DMZFW-VIP-ehsVRF
            peer_group: DMZFW-EBGP-PEERS-ehsVRF
            nodes:
              - ISMCR01A
              - ISMCR02A
            # changing next hop change is recommended via an outgoing route-map on sessions to the firewall for a faster failover
            set_ipv4_next_hop: 10.210.241.121
            # route_map_out: RM-DMZFW-DMZ-VRF-OUT
        structured_config:
          prefix_lists:
            - name: PL-LOCAL-NETWORKS-ehsVRF
              sequence_numbers:
                - sequence: 10
                  action: permit 10.210.241.120/29
                - sequence: 20
                  action: permit 10.210.241.32/29
          route_maps:
            - name: RM-LOCAL-NETWORKS-GehsVRF
              sequence_numbers:
                - sequence: 10
                  type: permit
                  match:
                    - "ip address prefix-list PL-LOCAL-NETWORKS-ehsVRF"
        #   route_maps:
        #     - name: RM-DMZFW-IoT-VRF-OUT
        #       sequence_numbers:
        #         - sequence: 10
        #           type: permit
        #           match:
        #             - "ip address prefix-list PL-DMZFW-DENY-HOST-ROUTES"
        #         - sequence: 20
        #           type: permit
        #           set:
        #             - ip next-hop 10.210.241.73
          router_bgp:
            vrfs:
              - name: ehs
                redistribute_routes:
                  - source_protocol: connected
                    route_map: RM-LOCAL-NETWORKS-ehsVRF
        static_routes:
        - destination_address_prefix: 0.0.0.0/0
          gateway: 10.210.241.126
          name: ISMPAN98&99-ehsVRF
          metric: 225
          distance: 225
          nodes:
            - ISMCR01A
            - ISMCR02A